import type { Role, RoleKey, PermissionAction } from "@/types/entities";

export const ROLES: Role[] = [
  { key: "administrador", nombre: "Administrador", descripcion: "Control total del sistema y configuración", nivel: 1 },
  { key: "gerente_general", nombre: "Gerente General", descripcion: "Visión global y aprobaciones estratégicas", nivel: 2 },
  { key: "director", nombre: "Director", descripcion: "Gestión por dirección y aprobaciones de segundo nivel", nivel: 3 },
  { key: "jefe", nombre: "Jefe", descripcion: "Gestión de área y aprobación de solicitudes", nivel: 4 },
  { key: "supervisor", nombre: "Supervisor", descripcion: "Control operativo del equipo a cargo", nivel: 5 },
  { key: "talento_humano", nombre: "Talento Humano", descripcion: "Administración de personal y documentación", nivel: 3 },
  { key: "nomina", nombre: "Nómina", descripcion: "Liquidación, novedades y reportes de nómina", nivel: 3 },
  { key: "contabilidad", nombre: "Contabilidad", descripcion: "Costos, causación y control presupuestal", nivel: 3 },
  { key: "sst", nombre: "SST", descripcion: "Seguridad y salud en el trabajo", nivel: 3 },
  { key: "empleado", nombre: "Empleado", descripcion: "Autogestión de su información y solicitudes", nivel: 9 },
];

export const ROLE_LABEL = Object.fromEntries(ROLES.map((r) => [r.key, r.nombre])) as Record<
  RoleKey,
  string
>;

/** Matriz de permisos por módulo: módulo -> rol -> acciones habilitadas. */
export type PermissionMatrix = Record<string, Partial<Record<RoleKey, PermissionAction[]>>>;

export const ALL_ACTIONS: PermissionAction[] = [
  "ver",
  "crear",
  "editar",
  "aprobar",
  "exportar",
  "inactivar",
];

/** Permisos base del núcleo. Los módulos funcionales se registrarán aquí. */
export const PERMISSION_MATRIX: PermissionMatrix = {
  dashboard: {
    administrador: ALL_ACTIONS,
    gerente_general: ["ver", "exportar"],
    director: ["ver", "exportar"],
    jefe: ["ver"],
    supervisor: ["ver"],
    talento_humano: ["ver", "exportar"],
    nomina: ["ver", "exportar"],
    sst: ["ver", "exportar"],
    contabilidad: ["ver", "exportar"],
    empleado: ["ver"],
  },
  maestros: {
    administrador: ALL_ACTIONS,
    talento_humano: ["ver", "crear", "editar", "exportar", "inactivar"],
    gerente_general: ["ver", "exportar"],
  },
  organizacion: {
    administrador: ALL_ACTIONS,
    gerente_general: ["ver", "aprobar", "exportar"],
    director: ["ver", "crear", "editar", "exportar"],
    talento_humano: ["ver", "crear", "editar", "exportar", "inactivar"],
    jefe: ["ver"],
    supervisor: ["ver"],
    contabilidad: ["ver", "exportar"],
    nomina: ["ver", "exportar"],
    empleado: ["ver"],
  },
  organigrama: {
    administrador: ALL_ACTIONS,
    gerente_general: ["ver", "exportar"],
    director: ["ver", "exportar"],
    talento_humano: ["ver", "editar", "exportar"],
    jefe: ["ver"],
    supervisor: ["ver"],
    empleado: ["ver"],
  },
  salarios: {
    administrador: ["ver", "editar", "exportar"],
    gerente_general: ["ver", "exportar"],
    director: ["ver", "exportar"],
    nomina: ["ver", "editar", "exportar"],
    contabilidad: ["ver", "exportar"],
    jefe: ["ver"],
    supervisor: ["ver"],
    empleado: ["ver"],
  },
  empleados: {
    administrador: ALL_ACTIONS,
    talento_humano: ALL_ACTIONS,
    gerente_general: ["ver", "exportar"],
    director: ["ver", "exportar"],
    jefe: ["ver"],
    supervisor: ["ver"],
    nomina: ["ver", "exportar"],
    contabilidad: ["ver", "exportar"],
    sst: ["ver"],
    empleado: ["ver"],
  },
  hoja_vida: {
    administrador: ["ver", "crear", "exportar"],
    talento_humano: ["ver", "crear", "exportar"],
    gerente_general: ["ver", "exportar"],
    director: ["ver", "exportar"],
    jefe: ["ver"],
    empleado: ["ver"],
  },
  portal: {
    administrador: ALL_ACTIONS,
    talento_humano: ALL_ACTIONS,
    empleado: ["ver", "crear"],
    jefe: ["ver"],
    supervisor: ["ver"],
    director: ["ver"],
    gerente_general: ["ver"],
  },
  solicitudes: {
    administrador: ALL_ACTIONS,
    talento_humano: ["ver", "aprobar", "editar", "exportar"],
    empleado: ["ver", "crear"],
    jefe: ["ver"],
    gerente_general: ["ver", "exportar"],
  },
  documentacion: {
    administrador: ALL_ACTIONS,
    talento_humano: ALL_ACTIONS,
    sst: ["ver", "crear", "exportar"],
    empleado: ["ver", "crear"],
    jefe: ["ver"],
    gerente_general: ["ver", "exportar"],
  },
  certificados: {
    administrador: ALL_ACTIONS,
    talento_humano: ["ver", "crear", "exportar"],
    empleado: ["ver", "crear"],
    nomina: ["ver", "crear"],
  },
  ausencias: {
    administrador: ALL_ACTIONS,
    talento_humano: ALL_ACTIONS,
    gerente_general: ["ver", "aprobar", "exportar"],
    director: ["ver", "aprobar", "exportar"],
    jefe: ["ver", "aprobar", "exportar"],
    supervisor: ["ver", "crear"],
    nomina: ["ver", "exportar"],
    sst: ["ver", "exportar"],
    empleado: ["ver", "crear"],
  },
  asistencia: {
    administrador: ALL_ACTIONS,
    supervisor: ["ver", "crear", "editar", "exportar"],
    jefe: ["ver", "crear", "editar", "exportar"],
    director: ["ver", "exportar"],
    gerente_general: ["ver", "exportar"],
    talento_humano: ["ver", "exportar"],
    nomina: ["ver", "exportar"],
    empleado: ["ver"],
  },
  horas_extras: {
    administrador: ALL_ACTIONS,
    supervisor: ["ver", "crear"],
    jefe: ["ver", "aprobar", "exportar"],
    director: ["ver", "aprobar", "exportar"],
    nomina: ["ver", "aprobar", "editar", "exportar"],
    contabilidad: ["ver", "exportar"],
    talento_humano: ["ver", "exportar"],
    gerente_general: ["ver", "exportar"],
    empleado: ["ver"],
  },
  novedades: {
    administrador: ["ver", "exportar"],
    talento_humano: ["ver", "exportar"],
    gerente_general: ["ver", "exportar"],
    director: ["ver", "exportar"],
    jefe: ["ver", "exportar"],
    supervisor: ["ver"],
    nomina: ["ver", "exportar"],
    contabilidad: ["ver", "exportar"],
    empleado: ["ver"],
  },
  usuarios: {
    administrador: ALL_ACTIONS,
    talento_humano: ["ver", "crear", "editar", "inactivar"],
    jefe: ["ver"],
  },
  sst: {
    administrador: ALL_ACTIONS,
    sst: ALL_ACTIONS,
    talento_humano: ["ver", "crear", "editar", "exportar"],
    gerente_general: ["ver", "exportar"],
    director: ["ver", "exportar"],
    jefe: ["ver"],
    supervisor: ["ver", "crear"],
    nomina: ["ver"],
    empleado: ["ver"],
  },
  dotacion: {
    administrador: ALL_ACTIONS,
    sst: ["ver", "crear", "editar", "exportar"],
    talento_humano: ALL_ACTIONS,
    supervisor: ["ver"],
    jefe: ["ver"],
    contabilidad: ["ver", "exportar"],
    empleado: ["ver", "aprobar"],
  },
  formularios: {
    administrador: ALL_ACTIONS,
    sst: ALL_ACTIONS,
    talento_humano: ALL_ACTIONS,
    gerente_general: ["ver", "exportar"],
    director: ["ver", "exportar"],
    jefe: ["ver"],
    supervisor: ["ver"],
    empleado: ["ver", "crear"],
  },
  disciplinario: {
    administrador: ALL_ACTIONS,
    talento_humano: ALL_ACTIONS,
    director: ["ver", "aprobar", "exportar"],
    jefe: ["ver", "crear", "aprobar", "exportar"],
    supervisor: ["ver", "crear"],
    gerente_general: ["ver", "exportar"],
  },
  observaciones: {
    administrador: ALL_ACTIONS,
    talento_humano: ALL_ACTIONS,
    director: ["ver", "crear"],
    jefe: ["ver", "crear"],
    supervisor: ["ver", "crear"],
  },
  evaluaciones: {
    administrador: ALL_ACTIONS,
    talento_humano: ALL_ACTIONS,
    sst: ALL_ACTIONS,
    gerente_general: ["ver", "exportar"],
    director: ["ver", "exportar"],
    jefe: ["ver", "exportar"],
    supervisor: ["ver"],
    empleado: ["ver", "crear"],
  },
  auditoria: {
    administrador: ["ver", "exportar"],
    gerente_general: ["ver", "exportar"],
  },
  configuracion: {
    administrador: ALL_ACTIONS,
  },
};

export function can(roles: RoleKey[], modulo: string, accion: PermissionAction): boolean {
  const modulePerms = PERMISSION_MATRIX[modulo];
  if (!modulePerms) return false;
  return roles.some((role) => modulePerms[role]?.includes(accion) ?? false);
}
