/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuditoriaRouteImport } from './routes/auditoria'
import { Route as ConfiguracionRouteImport } from './routes/configuracion'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MaestrosRouteImport } from './routes/maestros'
import { Route as OrganizacionRouteImport } from './routes/organizacion'
import { Route as UsuariosRouteImport } from './routes/usuarios'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditoriaRoute = AuditoriaRouteImport.update({
  id: '/auditoria',
  path: '/auditoria',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracionRoute = ConfiguracionRouteImport.update({
  id: '/configuracion',
  path: '/configuracion',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MaestrosRoute = MaestrosRouteImport.update({
  id: '/maestros',
  path: '/maestros',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizacionRoute = OrganizacionRouteImport.update({
  id: '/organizacion',
  path: '/organizacion',
  getParentRoute: () => rootRouteImport,
} as any)
const UsuariosRoute = UsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auditoria': typeof AuditoriaRoute
  '/configuracion': typeof ConfiguracionRoute
  '/login': typeof LoginRoute
  '/maestros': typeof MaestrosRoute
  '/organizacion': typeof OrganizacionRoute
  '/usuarios': typeof UsuariosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auditoria': typeof AuditoriaRoute
  '/configuracion': typeof ConfiguracionRoute
  '/login': typeof LoginRoute
  '/maestros': typeof MaestrosRoute
  '/organizacion': typeof OrganizacionRoute
  '/usuarios': typeof UsuariosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auditoria': typeof AuditoriaRoute
  '/configuracion': typeof ConfiguracionRoute
  '/login': typeof LoginRoute
  '/maestros': typeof MaestrosRoute
  '/organizacion': typeof OrganizacionRoute
  '/usuarios': typeof UsuariosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auditoria'
    | '/configuracion'
    | '/login'
    | '/maestros'
    | '/organizacion'
    | '/usuarios'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auditoria'
    | '/configuracion'
    | '/login'
    | '/maestros'
    | '/organizacion'
    | '/usuarios'
  id:
    | '__root__'
    | '/'
    | '/auditoria'
    | '/configuracion'
    | '/login'
    | '/maestros'
    | '/organizacion'
    | '/usuarios'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuditoriaRoute: typeof AuditoriaRoute
  ConfiguracionRoute: typeof ConfiguracionRoute
  LoginRoute: typeof LoginRoute
  MaestrosRoute: typeof MaestrosRoute
  OrganizacionRoute: typeof OrganizacionRoute
  UsuariosRoute: typeof UsuariosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auditoria': {
      id: '/auditoria'
      path: '/auditoria'
      fullPath: '/auditoria'
      preLoaderRoute: typeof AuditoriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracion': {
      id: '/configuracion'
      path: '/configuracion'
      fullPath: '/configuracion'
      preLoaderRoute: typeof ConfiguracionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maestros': {
      id: '/maestros'
      path: '/maestros'
      fullPath: '/maestros'
      preLoaderRoute: typeof MaestrosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizacion': {
      id: '/organizacion'
      path: '/organizacion'
      fullPath: '/organizacion'
      preLoaderRoute: typeof OrganizacionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/usuarios': {
      id: '/usuarios'
      path: '/usuarios'
      fullPath: '/usuarios'
      preLoaderRoute: typeof UsuariosRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuditoriaRoute: AuditoriaRoute,
  ConfiguracionRoute: ConfiguracionRoute,
  LoginRoute: LoginRoute,
  MaestrosRoute: MaestrosRoute,
  OrganizacionRoute: OrganizacionRoute,
  UsuariosRoute: UsuariosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
